#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 16:05:20 2018

@author: waldo
"""

import string
import ShiftCypher.shift_string as shift

l = list(string.ascii_letters)

if __name__ == '__main__':
    data = input('Enter string to decode')
    for i in range(1,len(l)):
        print (str(i), shift(data, i) )